name: Package

on:
  pull_request:

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Mise
        uses: immich-app/devtools/actions/use-mise@7b8610a904d57da241e4ddba17fa62b62b15aed4 # use-mise-action-v2.0.2

      - name: Checkout assets
        run: mise assets

      - name: Install dependencies
        run: mise install:frozen

      - name: Package
        run: mise build

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: stoat-linux-package-x64
          path: ./out/Stoat-linux-x64
